export const MOCK_MARKNADSSOK = [
  {
    dateOfPublication: new Date("2019-09-12").toLocaleDateString(),
    issuer: "Arbona AB",
    name: "Håkan Blomdahl",
    title: "Styrelseledamot/suppleant",
    closelyRelatedPerson: true,
    transactionType: "Teckning",
    instrument: "Arbona BTA",
    isin: "SE0013050606",
    dateOfTransaction: new Date("2019-09-11").toLocaleDateString(),
    volume: 5875974,
    price: 1.35,
    currency: "SEK",
    exchange: "Utanför handelsplats",
  },
  {
    dateOfPublication: new Date("2019-09-12").toLocaleDateString(),
    issuer: "Arbona AB",
    name: "Håkan Blomdahl",
    title: "Styrelseledamot/suppleant",
    closelyRelatedPerson: true,
    transactionType: "Teckning",
    instrument: "Arbona BTA",
    isin: "SE0013050606",
    dateOfTransaction: new Date("2019-09-12").toLocaleDateString(),
    volume: 300760,
    price: 0.155,
    currency: "SEK",
    exchange: "NORDIC MTF",
  },
  {
    dateOfPublication: new Date("2019-09-12").toLocaleDateString(),
    issuer: "Scandinavian Enviro Systems AB",
    name: "Nils Lennart Persson",
    title: "Styrelseledamot/suppleant",
    closelyRelatedPerson: false,
    transactionType: "Lösen ökning",
    instrument: "Scandinavian Enviro Systems AB",
    isin: "SE0005877560",
    dateOfTransaction: new Date("2019-09-12").toLocaleDateString(),
    volume: 4761810,
    price: 0.4,
    currency: "SEK",
    exchange: "Utanför handelsplats",
  },
  {
    dateOfPublication: new Date("2019-09-12").toLocaleDateString(),
    issuer: "Scandinavian Enviro Systems AB",
    name: "Nils Lennart Persson",
    title: "Styrelseledamot/suppleant",
    closelyRelatedPerson: false,
    transactionType: "Lösen minskning",
    instrument: "To2",
    isin: "SE0012011138",
    dateOfTransaction: new Date("2019-09-12").toLocaleDateString(),
    volume: 813256,
    price: 0.0,
    currency: "SEK",
    exchange: "Utanför handelsplats",
  },
  {
    dateOfPublication: new Date("2019-09-12").toLocaleDateString(),
    issuer: "Sivers IMA Holding AB",
    name: "Sven Pettersson",
    title: "VP R&D",
    closelyRelatedPerson: false,
    transactionType: "Avyttring",
    instrument: "SIVE TO19",
    isin: "",
    dateOfTransaction: new Date("2019-09-11").toLocaleDateString(),
    volume: 80000,
    price: 2.403645,
    currency: "SEK",
    exchange: "Utanför handelsplats",
  },
  {
    dateOfPublication: new Date("2019-09-12").toLocaleDateString(),
    issuer: "Asarina Pharma AB",
    name: "Miroslav Reljanovic",
    title: "Board member/Board Deputy",
    closelyRelatedPerson: true,
    transactionType: "Avyttring",
    instrument: "Asarina Pharma AB Shares",
    isin: "SE0011641794",
    dateOfTransaction: new Date("2019-09-10").toLocaleDateString(),
    volume: 58934,
    price: 25.9367,
    currency: "SEK",
    exchange: "FIRST NORTH SWEDEN",
  },
  {
    dateOfPublication: new Date("2019-09-12").toLocaleDateString(),
    issuer: "Asarina Pharma AB",
    name: "Miroslav Reljanovic",
    title: "Board member/Board Deputy",
    closelyRelatedPerson: true,
    transactionType: "Avyttring",
    instrument: "Asarina Pharma AB Shares",
    isin: "SE0011641794",
    dateOfTransaction: new Date("2019-09-11").toLocaleDateString(),
    volume: 5114,
    price: 25.9,
    currency: "SEK",
    exchange: "FIRST NORTH SWEDEN",
  },
  {
    dateOfPublication: new Date("2019-09-12").toLocaleDateString(),
    issuer: "Avanza Bank Holding AB (publ)",
    name: "Peter Strömberg",
    title: "CIO",
    closelyRelatedPerson: true,
    transactionType: "Utbyte minskning",
    instrument: "Interimsaktie",
    isin: "",
    dateOfTransaction: new Date("2019-09-10").toLocaleDateString(),
    volume: 42828,
    price: 0.0,
    currency: "SEK",
    exchange: "FIRST NORTH SWEDEN",
  },
  {
    dateOfPublication: new Date("2019-09-12").toLocaleDateString(),
    issuer: "Sivers IMA Holding AB",
    name: "Anders Storm",
    title: "VD",
    closelyRelatedPerson: false,
    transactionType: "Förvärv",
    instrument: "SIVE TO19",
    isin: "",
    dateOfTransaction: new Date("2019-09-11").toLocaleDateString(),
    volume: 750000,
    price: 2.403645,
    currency: "SEK",
    exchange: "Utanför handelsplats",
  },
  {
    dateOfPublication: new Date("2019-09-11").toLocaleDateString(),
    issuer: "Sivers IMA Holding AB",
    name: "Anders Storm",
    title: "VD",
    closelyRelatedPerson: false,
    transactionType: "Förvärv",
    instrument: "Sivers IMA",
    isin: "SE0003917798",
    dateOfTransaction: new Date("2019-09-12").toLocaleDateString(),
    volume: 26200,
    price: 7.4,
    currency: "SEK",
    exchange: "NASDAQ STOCKHOLM AB",
  },
  {
    dateOfPublication: new Date("2019-09-11").toLocaleDateString(),
    issuer: "Sivers IMA Holding AB",
    name: "Mats Carlsson",
    title: "CTO",
    closelyRelatedPerson: false,
    transactionType: "Avyttring",
    instrument: "SIVE TO19",
    isin: "",
    dateOfTransaction: new Date("2019-09-11").toLocaleDateString(),
    volume: 26200,
    price: 2.403645,
    currency: "SEK",
    exchange: "Utanför handelsplats",
  },
]

export const MOCK_XY_VALUES = [
  {
    x: new Date("2019-09-02").toLocaleDateString(),
    y: 10000.0,
  },
  {
    x: new Date("2019-09-03").toLocaleDateString(),
    y: -50000.0,
  },
  {
    x: new Date("2019-09-04").toLocaleDateString(),
    y: 53000.0,
  },
  {
    x: new Date("2019-09-05").toLocaleDateString(),
    y: 75000.0,
  },
  {
    x: new Date("2019-09-06").toLocaleDateString(),
    y: 15000.0,
  },
  {
    x: new Date("2019-09-07").toLocaleDateString(),
    y: 1000.0,
  },
]

export const MOCK_DATES = ["2019-09-10", "2019-09-11", "2019-09-12"]
